import { describe,expect,it } from "vitest";
import { mkdtemp,writeFile } from "node:fs/promises";
import { join } from "node:path";import { tmpdir } from "node:os";
import { loadContentStrategy } from "../src/content-ai/strategy.js";
import { planSeeds,CONTENT_LIMITS } from "../src/content-ai/planner.js";
import { deterministicDuplicate } from "../src/content-ai/duplicate-reviewer.js";
import { redactAIError,validatePublicDraft } from "../src/content-ai/safety.js";
import { ThreadsContentService } from "../src/content-ai/service.js";
import { loadContentAIConfig } from "../src/config.js";
import type { AIContext,ContentAIProvider,ContentAIRunLog,ContentLedgerRecord,ContentPlanRecord,ContentStore,DraftCandidate,DuplicateReview,PlanSeed } from "../src/content-ai/types.js";
import type { PostHistoryRecord,PostQueueRecord,PostStore } from "../src/posting/types.js";
const strategy={language:"ja",voice:"自然",audience:["副業を始める人"],contentPillars:["副業","時間管理","学び"],avoidTopics:[],styleRules:["自然に"],publicDisclosureRules:["自動化を公開しない"],verifiedFacts:[]};
class MemoryStore implements ContentStore,PostStore{plans=new Map<string,ContentPlanRecord>();ledger=new Map<string,ContentLedgerRecord>();posts=new Map<string,PostQueueRecord>();logs:ContentAIRunLog[]=[];history:PostHistoryRecord[]=[];async ensureContentSheets(){}async ensurePostSheets(){}async listPlans(){return[...this.plans.values()]}async upsertPlan(x:ContentPlanRecord){this.plans.set(x.planId,x)}async listLedger(){return[...this.ledger.values()]}async upsertLedger(x:ContentLedgerRecord){this.ledger.set(x.contentId,x)}async appendRunLog(x:ContentAIRunLog){this.logs.push(x)}async readThreadsPerformance(){return[]}async listPosts(){return[...this.posts.values()]}async getPost(id:string){return this.posts.get(id)??null}async upsertPost(x:PostQueueRecord){this.posts.set(x.postId,x)}async appendHistory(x:PostHistoryRecord){this.history.push(x)}}
const candidate=(content="限られた時間では、作業を小さく区切ると始めやすいです。"):DraftCandidate=>({content,coreTheme:"限られた時間",claim:"小さく区切る",readerValue:"始めやすくなる",advice:"15分単位にする",angle:"実践",hookType:"気づき",contentSummary:"時間を小さく区切る"});
class Provider implements ContentAIProvider{readonly name="mock";readonly model="mock-1";constructor(private draft=candidate(),private review:DuplicateReview={status:"UNIQUE",matchedContentId:"",reason:"new"}){}async generatePlan(seeds:PlanSeed[]){return seeds.map(x=>({...x,coreTheme:`${x.contentPillar}テーマ`,angle:"実践",goal:"気づき",hookIdea:"日常"}))}async generateDraft(){return this.draft}async reviewDuplicate(){return this.review}}
const now=()=>new Date("2026-08-31T00:00:00Z");
describe("Threads Content AI",()=>{
 it("parses strategy config",async()=>{const dir=await mkdtemp(join(tmpdir(),"strategy-")),path=join(dir,"s.json");await writeFile(path,JSON.stringify(strategy));expect((await loadContentStrategy(path)).contentPillars).toHaveLength(3);});
 it("creates balanced plans from the next Tokyo date and enforces max",()=>{const seeds=planSeeds(2,3,strategy,new Date("2026-08-30T16:00:00Z"));expect(seeds[0]?.targetDate).toBe("2026-09-01");expect(seeds.map(x=>x.contentPillar)).toEqual(["副業","時間管理","学び","副業","時間管理","学び"]);expect(()=>planSeeds(8,3,strategy,now())).toThrow(String(CONTENT_LIMITS.maxPerRun));});
 it("detects rephrased semantic duplicate and unique",()=>{const ledger=[{contentId:"old",postId:"",platform:"threads",createdAt:"",publishedAt:"",status:"PUBLISHED",coreTheme:"限られた時間",claim:"小さく区切る",readerValue:"始めやすくなる",advice:"15分単位にする",contentPillar:"時間管理",angle:"",hookType:"",contentSummary:"",sourceType:"manual",performanceTier:"INSUFFICIENT_DATA",notes:""} as ContentLedgerRecord];expect(deterministicDuplicate(candidate(),ledger).status).toBe("DUPLICATE");expect(deterministicDuplicate(candidate("別の話"),[]).status).toBe("UNIQUE");});
 it("inserts UNIQUE as DRAFT and possible duplicate as REVIEW",async()=>{for(const review of [{status:"UNIQUE",matchedContentId:"",reason:"new"},{status:"POSSIBLE_DUPLICATE",matchedContentId:"old",reason:"similar"}] as DuplicateReview[]){const store=new MemoryStore(),service=new ThreadsContentService(store,store,new Provider(candidate(review.status==="UNIQUE"?"固有の投稿案です。":"類似しそうな別候補です。"),review),strategy,now);await service.createPlan(1,1);await service.generate({count:1});expect([...store.posts.values()][0]?.status).toBe(review.status==="UNIQUE"?"DRAFT":"REVIEW");}});
 it("does not insert semantic DUPLICATE",async()=>{const store=new MemoryStore(),service=new ThreadsContentService(store,store,new Provider(candidate(),{status:"DUPLICATE",matchedContentId:"old",reason:"same"}),strategy,now);await service.createPlan(1,1);await service.generate({count:1});expect(store.posts.size).toBe(0);expect([...store.plans.values()][0]?.status).toBe("SKIPPED_DUPLICATE");});
 it("does not insert an exact Queue duplicate even if AI says UNIQUE",async()=>{const store=new MemoryStore(),first=new ThreadsContentService(store,store,new Provider(),strategy,now);await first.createPlan(1,1);await first.generate({count:1});const plan=[...store.plans.values()][0]!;store.plans.set(plan.planId,{...plan,status:"PLANNED",generatedPostId:""});const second=new ThreadsContentService(store,store,new Provider(),strategy,now);await second.generate({count:1});expect(store.posts.size).toBe(1);expect([...store.plans.values()][0]?.status).toBe("SKIPPED_DUPLICATE");});
 it("dry-run does not mutate Queue or Plan status",async()=>{const store=new MemoryStore(),service=new ThreadsContentService(store,store,new Provider(),strategy,now);await service.createPlan(1,1);await service.generate({count:1,dryRun:true});expect(store.posts.size).toBe(0);expect([...store.plans.values()][0]?.status).toBe("PLANNED");expect(store.logs.at(-1)?.status).toBe("DRY_RUN");});
 it("rejects without deleting and regenerates with a limit",async()=>{const store=new MemoryStore(),service=new ThreadsContentService(store,store,new Provider(),strategy,now);await service.createPlan(1,1);await service.generate({count:1});const plan=[...store.plans.values()][0]!;expect((await service.reject(plan.planId)).status).toBe("REJECTED");expect(store.posts.size).toBe(1);await service.regenerate(plan.planId,true);expect([...store.plans.values()][0]?.regenerationCount).toBe(1);});
 it("blocks disclosures and fake achievements",()=>{expect(validatePublicDraft("launchdで自動投稿しています",strategy)).toContain("PUBLIC_DISCLOSURE_BLOCKED");expect(validatePublicDraft("月10万円稼ぎました",strategy)).toContain("UNVERIFIED_ACHIEVEMENT");});
 it("requires API key only for AI config",()=>{expect(()=>loadContentAIConfig({CONTENT_AI_PROVIDER:"openai"})).toThrow("OPENAI_API_KEY");expect(loadContentAIConfig({CONTENT_AI_PROVIDER:"openai",OPENAI_API_KEY:"test-key"}).model).toBe("gpt-5-mini");});
 it("redacts secrets from provider errors",()=>{const secret=["sk","placeholder","123456789"].join("-");expect(redactAIError(new Error(`failed ${secret}`))).not.toContain("placeholder");});
});
