import { describe, expect, it } from "vitest";
import { ThreadsApiError, type ThreadsPublishingApi } from "../src/threads-client.js";
import { duplicateCheck } from "../src/posting/duplicate.js";
import { formatImportErrorDetails, ThreadsPostService } from "../src/posting/service.js";
import { assertTransition } from "../src/posting/state.js";
import type { PostHistoryRecord, PostQueueRecord, PostStore } from "../src/posting/types.js";
import type { PublisherRunLogRecord, PublisherRunStore } from "../src/posting/types.js";
import { readPostCandidates } from "../src/posting/batch.js";
import { writeFile, mkdtemp } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";

class MemoryStore implements PostStore, PublisherRunStore {
  posts = new Map<string, PostQueueRecord>(); history: PostHistoryRecord[] = []; runs: PublisherRunLogRecord[]=[];ensureCalls=0;listCalls=0;appendCalls=0;updateCalls=0;
  async ensurePostSheets() {this.ensureCalls++;} async listPosts() {this.listCalls++;return [...this.posts.values()]; } async getPost(id: string) { return this.posts.get(id) ?? null; }
  async upsertPost(post: PostQueueRecord) { this.posts.set(post.postId, post); } async appendPosts(records:PostQueueRecord[]){this.appendCalls++;for(const record of records)this.posts.set(record.postId,record);}async updatePosts(records:PostQueueRecord[]){this.updateCalls++;for(const record of records)this.posts.set(record.postId,record);} async appendHistory(value: PostHistoryRecord) { this.history.push(value); }
  async appendPublisherRunLog(value:PublisherRunLogRecord){this.runs.push(value);}
}
const now = () => new Date("2026-08-29T00:00:00Z");
const api = (failure?: Error): ThreadsPublishingApi => ({ async getProfile() { if (failure) throw failure; return { id: "redacted" }; }, async createTextContainer() { if (failure) throw failure; return "container"; }, async publishContainer() { if (failure) throw failure; return "thread-post"; } });
async function scheduled(store = new MemoryStore(), client = api()) { const service = new ThreadsPostService(store, client, now), post = await service.addDraft("安全なテスト投稿候補"); const approved=await service.approve(post.postId);await store.upsertPost({...approved,status:"SCHEDULED",scheduledAt:"2026-08-28T23:00:00Z"}); return { service, store, postId: post.postId }; }

describe("Threads posting queue", () => {
  it("adds DRAFT and rejects empty content", async () => { const service = new ThreadsPostService(new MemoryStore(), undefined, now); expect((await service.addDraft(" hello ")).status).toBe("DRAFT"); await expect(service.addDraft("  ")).rejects.toThrow("empty"); });
  it("blocks exact published duplicates and warns on near duplicates", async () => {
    const store = new MemoryStore(), service = new ThreadsPostService(store, undefined, now), first = await service.addDraft("同じ内容 https://example.com #tag"); first.status = "PUBLISHED"; await store.upsertPost(first);
    expect((await service.addDraft("同じ内容 https://example.com #tag")).status).toBe("SKIPPED_DUPLICATE");
    const near = await service.addDraft("同じ内容 https://other.example #other"); expect(near.status).toBe("REVIEW"); expect(near.notes).toContain("NEAR_DUPLICATE_WARNING");
  });
  it("allows valid transitions and rejects invalid ones", () => { expect(() => assertTransition("DRAFT", "APPROVED")).not.toThrow(); expect(() => assertTransition("PUBLISHED", "SCHEDULED")).toThrow("Invalid"); expect(() => assertTransition("FAILED", "PUBLISHED")).toThrow("Invalid"); });
  it("approves and schedules with timezone validation", async () => { const service = new ThreadsPostService(new MemoryStore(), undefined, now), post = await service.addDraft("candidate"); expect((await service.approve(post.postId)).status).toBe("APPROVED"); await expect(service.schedule(post.postId, "2026-09-01 10:00")).rejects.toThrow("timezone"); expect((await service.schedule(post.postId, "2026-09-01T10:00:00+09:00")).status).toBe("SCHEDULED"); });
  it("does not mark a future scheduled post due", async () => { const service = new ThreadsPostService(new MemoryStore(), api(), now), post = await service.addDraft("future"); await service.approve(post.postId); await service.schedule(post.postId, "2026-09-01T10:00:00+09:00"); expect((await service.dryRun(post.postId))).toMatchObject({ publishable: false, reason: "NOT_DUE" }); expect(await service.publishDue()).toMatchObject({dueCount:0,targets:[]}); });
  it("publishes through two API steps, appends history, and is idempotent", async () => { const { service, store, postId } = await scheduled(); expect((await service.publish(postId)).status).toBe("PUBLISHED"); expect(store.history).toHaveLength(1); expect(store.history[0]?.status).toBe("PUBLISHED"); expect((await service.publish(postId)).status).toBe("SKIPPED"); expect(store.history).toHaveLength(1); });
  it("records API failure and retry count with no secret", async () => { const secret = "token-secret-value", setup = await scheduled(new MemoryStore(), api(new Error(`API failed access_token=${secret}`))); const result = await setup.service.publish(setup.postId); expect(result.post).toMatchObject({ status: "FAILED", retryCount: 1 }); expect(result.post.errorMessage).not.toContain(secret); expect(setup.store.history[0]?.status).toBe("FAILED"); });
  it.each([[new ThreadsApiError("THREADS_190", "expired"), "AUTH_ERROR"], [new ThreadsApiError("THREADS_429", "limited"), "RATE_LIMIT"]] as const)("classifies API errors", async (error, code) => { const setup = await scheduled(new MemoryStore(), api(error)); expect((await setup.service.publish(setup.postId)).post.errorCode).toBe(code); });
  it("enforces retry limit", async () => { const setup = await scheduled(new MemoryStore(), api(new Error("failure"))); await setup.service.publish(setup.postId); await setup.service.publish(setup.postId); await setup.service.publish(setup.postId); await expect(setup.service.publish(setup.postId)).rejects.toThrow("retry limit"); expect((await setup.store.getPost(setup.postId))?.retryCount).toBe(3); });
  it("continues due publishing after one failure", async () => { const store = new MemoryStore(); let calls = 0; const client: ThreadsPublishingApi = { async getProfile(){return{id:"x"};}, async createTextContainer(){calls++; if(calls===1) throw new Error("first failed"); return "c";}, async publishContainer(){return "p";} }; const first=await scheduled(store,client), secondPost=await first.service.addDraft("second"); const approved=await first.service.approve(secondPost.postId);await store.upsertPost({...approved,status:"SCHEDULED",scheduledAt:"2026-08-28T23:30:00Z"}); const results=await first.service.publishDue(); expect(results).toMatchObject({failedCount:1,publishedCount:1}); });
  it("detects exact duplicates only against protected statuses", async () => { const { store } = await scheduled(); const posts=await store.listPosts(); expect(duplicateCheck(posts[0]!.content,posts,"other").exact).toBe(true); });
  it("imports rows without auto approval or scheduling and isolates invalid rows",async()=>{const store=new MemoryStore(),service=new ThreadsPostService(store,undefined,now);const result=await service.importCandidates([{content:"valid",scheduledAt:"2026-09-01T08:00:00+09:00",notes:"a"},{content:"",scheduledAt:"",notes:"bad"}]);expect(result).toMatchObject({read:2,draft:1,errors:1,errorDetails:[{row:2,preview:"",scheduledAt:"",error:"Post content must not be empty"}]});expect(result.posts).toHaveLength(1);expect(result.posts[0]).toMatchObject({status:"DRAFT",scheduledAt:"",requestedScheduledAt:"2026-08-31T23:00:00.000Z"});});
  it("formats safe row-level import errors for CLI output",async()=>{const store=new MemoryStore(),service=new ThreadsPostService(store,undefined,now);const result=await service.importCandidates([{content:"a long preview that is safe to show in diagnostic output and continues",scheduledAt:"invalid",notes:""}]);const output=formatImportErrorDetails(result.errorDetails);expect(output).toContain("エラー詳細:");expect(output).toContain("row=1");expect(output).toContain('scheduledAt="invalid"');expect(output).toContain('error="invalid scheduledAt"');expect(output).not.toContain("continues");});
  it("classifies exact and near duplicates during import",async()=>{const store=new MemoryStore(),service=new ThreadsPostService(store,undefined,now),published=await service.addDraft("same text https://example.com #one");await store.upsertPost({...published,status:"PUBLISHED"});const result=await service.importCandidates([{content:"same text https://example.com #one",scheduledAt:"",notes:""},{content:"same text https://other.example #two",scheduledAt:"",notes:""}]);expect(result).toMatchObject({read:2,duplicate:1,review:1,errors:0});expect(result.posts.map(p=>p.status)).toEqual(["REVIEW"]);});
  it("imports 21 rows with one ensure, one list and one batch append",async()=>{const store=new MemoryStore(),service=new ThreadsPostService(store,undefined,now),rows=Array.from({length:21},(_,i)=>({content:`candidate ${i}`,scheduledAt:"",notes:""}));await service.importCandidates(rows);expect(store.ensureCalls).toBe(1);expect(store.listCalls).toBe(1);expect(store.appendCalls).toBe(1);expect(store.posts.size).toBe(21);});
  it("is idempotent across repeated imports and counts exact DRAFT duplicates",async()=>{const store=new MemoryStore(),service=new ThreadsPostService(store,undefined,now),rows=[{content:"exact draft",scheduledAt:"",notes:""}];expect(await service.importCandidates(rows)).toMatchObject({draft:1,duplicate:0});expect(await service.importCandidates(rows)).toMatchObject({draft:0,duplicate:1});expect(store.posts.size).toBe(1);});
  it("does not multiply exact duplicates within one CSV",async()=>{const store=new MemoryStore(),service=new ThreadsPostService(store,undefined,now),result=await service.importCandidates([{content:"same",scheduledAt:"",notes:""},{content:"same",scheduledAt:"",notes:""}]);expect(result).toMatchObject({draft:1,duplicate:1});expect(store.posts.size).toBe(1);});
  it("keeps near imports in REVIEW",async()=>{const store=new MemoryStore(),service=new ThreadsPostService(store,undefined,now);await service.importCandidates([{content:"near text https://one.example #one",scheduledAt:"",notes:""}]);const result=await service.importCandidates([{content:"near text https://two.example #two",scheduledAt:"",notes:""}]);expect(result).toMatchObject({review:1,duplicate:0});expect(store.posts.size).toBe(2);});
  it("cleanup dry-run selects only later import DRAFT/REVIEW duplicates with one read",async()=>{const store=new MemoryStore(),service=new ThreadsPostService(store,undefined,now),base=await service.addDraft("cleanup duplicate","","import"),later={...base,postId:"later",status:"REVIEW" as const,createdAt:"2026-08-30T00:00:00.000Z",updatedAt:"2026-08-30T00:00:00.000Z"},approved={...base,postId:"approved",status:"APPROVED" as const,createdAt:"2026-08-31T00:00:00.000Z"},published={...base,postId:"published",status:"PUBLISHED" as const,createdAt:"2026-08-31T01:00:00.000Z"},manual={...base,postId:"manual",source:"manual" as const,createdAt:"2026-09-01T00:00:00.000Z"};await store.upsertPost(later);await store.upsertPost(approved);await store.upsertPost(published);await store.upsertPost(manual);store.ensureCalls=store.listCalls=store.updateCalls=0;const result=await service.cleanupImportDuplicates(false);expect(result.targets.map(x=>x.postId)).toEqual(["later"]);expect(store.ensureCalls).toBe(1);expect(store.listCalls).toBe(1);expect(store.updateCalls).toBe(0);expect([...store.posts.values()].every(x=>x.status!=="CANCELLED")).toBe(true);});
  it("approve-all approves DRAFT and excludes REVIEW",async()=>{const store=new MemoryStore(),service=new ThreadsPostService(store,undefined,now),draft=await service.addDraft("draft"),review=await service.addDraft("draft https://example.com");expect(review.status).toBe("REVIEW");expect((await service.approveAll({status:"DRAFT"})).map(x=>x.postId)).toEqual([draft.postId]);expect((await store.getPost(review.postId))?.status).toBe("REVIEW");});
  it("batch-approves 21 DRAFT with one PostQueue read",async()=>{const store=new MemoryStore(),service=new ThreadsPostService(store,undefined,now);await service.importCandidates(Array.from({length:21},(_,i)=>({content:`承認候補${String.fromCodePoint(0x4e00+i)}`,scheduledAt:"",notes:""})));store.ensureCalls=store.listCalls=store.updateCalls=0;const result=await service.approveAll({status:"DRAFT"});expect(result).toHaveLength(21);expect(result.every(post=>post.status==="APPROVED")).toBe(true);expect(store.ensureCalls).toBe(1);expect(store.listCalls).toBe(1);expect(store.updateCalls).toBe(1);});
  it("batch-approve safely resumes a partial 5 APPROVED plus 16 DRAFT state",async()=>{const store=new MemoryStore(),service=new ThreadsPostService(store,undefined,now);await service.importCandidates(Array.from({length:21},(_,i)=>({content:`部分状態${String.fromCodePoint(0x4e20+i)}`,scheduledAt:"",notes:""})));for(const post of [...store.posts.values()].slice(0,5))await store.upsertPost({...post,status:"APPROVED",approvedAt:now().toISOString()});store.listCalls=store.updateCalls=0;const result=await service.approveAll({status:"DRAFT"});expect(result).toHaveLength(16);expect([...store.posts.values()].filter(post=>post.status==="APPROVED")).toHaveLength(21);expect(store.listCalls).toBe(1);expect(store.updateCalls).toBe(1);});
  it("batch-schedules 21 imported APPROVED posts with one PostQueue read",async()=>{const store=new MemoryStore(),service=new ThreadsPostService(store,undefined,now),rows=Array.from({length:21},(_,i)=>({content:`予約候補${String.fromCodePoint(0x4e40+i)}`,scheduledAt:`2026-09-${String(i+1).padStart(2,"0")}T08:00:00+09:00`,notes:""}));await service.importCandidates(rows);await service.approveAll({status:"DRAFT"});store.ensureCalls=store.listCalls=store.updateCalls=0;const result=await service.scheduleImported();expect(result).toHaveLength(21);expect(result.every(post=>post.status==="SCHEDULED")).toBe(true);expect(store.ensureCalls).toBe(1);expect(store.listCalls).toBe(1);expect(store.updateCalls).toBe(1);});
  it("dry-runs deterministic jitter for 21 approved imports with one read and zero writes",async()=>{const store=new MemoryStore(),service=new ThreadsPostService(store,undefined,now),rows=Array.from({length:7},(_,day)=>[["08:00","朝"],["12:00","昼"],["21:00","夜"]].map(([time,label],slot)=>({content:`${label}候補${String.fromCodePoint(0x4e80+day*3+slot)}`,scheduledAt:`2026-09-${String(day+8).padStart(2,"0")}T${time}:00+09:00`,notes:""}))).flat();await service.importCandidates(rows);await service.approveAll({status:"DRAFT"});store.ensureCalls=store.listCalls=store.updateCalls=0;const first=await service.scheduleImported({jitter:true,dryRun:true}),second=await service.scheduleImported({jitter:true,dryRun:true});expect(first).toHaveLength(21);expect(first.map(post=>post.scheduledAt)).toEqual(second.map(post=>post.scheduledAt));for(let slot=0;slot<3;slot++)expect(new Set(first.filter((_,index)=>index%3===slot).map(post=>post.scheduledAt.slice(11,16))).size).toBe(7);expect(first.every(post=>post.status==="SCHEDULED")).toBe(true);expect([...store.posts.values()].every(post=>post.status==="APPROVED")).toBe(true);expect(store.listCalls).toBe(2);expect(store.updateCalls).toBe(0);});
  it("jitter never schedules DRAFT or REVIEW and avoids an existing scheduled collision",async()=>{const store=new MemoryStore(),service=new ThreadsPostService(store,undefined,now);await service.importCandidates([{content:"承認対象",scheduledAt:"2026-09-08T08:00:00+09:00",notes:""},{content:"未承認対象",scheduledAt:"2026-09-08T12:00:00+09:00",notes:""}]);const [approved,draft]=[...store.posts.values()];await store.upsertPost({...approved!,status:"APPROVED"});await store.upsertPost({...draft!,status:"REVIEW"});await store.upsertPost({...approved!,postId:"existing",content:"既存予約",contentHash:"existing",status:"SCHEDULED",scheduledAt:"2026-09-08T07:00:00+09:00",requestedScheduledAt:"",source:"manual"});const result=await service.scheduleImported({jitter:true,dryRun:true});expect(result).toHaveLength(1);expect(Date.parse(result[0]!.scheduledAt)-Date.parse("2026-09-08T07:00:00+09:00")).toBeGreaterThanOrEqual(60*60000);expect((await store.getPost(draft!.postId))?.status).toBe("REVIEW");});
  it("schedule-imported preserves approval, future, timezone and interval validation",async()=>{const store=new MemoryStore(),service=new ThreadsPostService(store,undefined,now);await service.importCandidates([{content:"needs approval",scheduledAt:"2026-09-01T08:00:00+09:00",notes:""}]);expect(await service.scheduleImported()).toEqual([]);const draft=[...store.posts.values()][0]!;await store.upsertPost({...draft,status:"APPROVED"});await store.upsertPost({...draft,postId:"invalid",content:"invalid",contentHash:"invalid",status:"APPROVED",requestedScheduledAt:"2026-09-01 08:00"});await expect(service.scheduleImported()).rejects.toThrow("timezone");expect([...store.posts.values()].every(post=>post.status!=="SCHEDULED")).toBe(true);});
  it("schedule-imported rejects in-batch collisions without partial writes",async()=>{const store=new MemoryStore(),service=new ThreadsPostService(store,undefined,now);await service.importCandidates([{content:"衝突候補甲",scheduledAt:"2026-09-01T08:00:00+09:00",notes:""},{content:"衝突候補乙",scheduledAt:"2026-09-01T08:30:00+09:00",notes:""}]);await service.approveAll({status:"DRAFT"});store.updateCalls=0;await expect(service.scheduleImported()).rejects.toThrow("at least 60");expect(store.updateCalls).toBe(0);expect([...store.posts.values()].every(post=>post.status==="APPROVED")).toBe(true);});
  it("schedules batches in JST and enforces interval, future, and collisions",async()=>{const store=new MemoryStore(),service=new ThreadsPostService(store,undefined,now);for(const text of ["a","b","c"]){const p=await service.addDraft(text);await service.approve(p.postId);}const scheduled=await service.scheduleBatch("2026-09-01T08:00:00+09:00",["08:00","12:00"]);expect(scheduled.map(x=>x.scheduledAt)).toEqual(["2026-08-31T23:00:00.000Z","2026-09-01T03:00:00.000Z","2026-09-01T23:00:00.000Z"]);const p=await service.addDraft("d");await service.approve(p.postId);await expect(service.schedule(p.postId,"2026-09-01T12:30:00+09:00")).rejects.toThrow("at least 60");await expect(service.schedule(p.postId,"2026-08-01T12:00:00+09:00")).rejects.toThrow("future");});
  it("dry-runs due and expires posts beyond six hours without publishing",async()=>{const store=new MemoryStore(),service=new ThreadsPostService(store,api(),now,store),p=await service.addDraft("old");const approved=await service.approve(p.postId);await store.upsertPost({...approved,status:"SCHEDULED",scheduledAt:"2026-08-28T10:00:00Z"});const preview=await service.publishDue(true);expect(preview).toMatchObject({dueCount:1,expiredCount:0,dryRun:true});expect(preview.targets[0]?.action).toBe("EXPIRE");expect((await store.getPost(p.postId))?.status).toBe("SCHEDULED");const actual=await service.publishDue(false);expect(actual.expiredCount).toBe(1);expect((await store.getPost(p.postId))?.status).toBe("EXPIRED");expect(store.history[0]?.status).toBe("EXPIRED");expect(store.runs.at(-1)?.overallStatus).toBe("SUCCESS");});
  it("parses BOM CSV and quoted newlines",async()=>{const dir=await mkdtemp(join(tmpdir(),"posts-")),path=join(dir,"posts.csv");await writeFile(path,"\uFEFFcontent,scheduledAt,notes\n\"line1\nline2\",,\"memo\"\n");expect(await readPostCandidates(path)).toEqual([{content:"line1\nline2",scheduledAt:"",notes:"memo"}]);});
  it("parses JSON candidates through the same schema",async()=>{const dir=await mkdtemp(join(tmpdir(),"posts-json-")),path=join(dir,"posts.json");await writeFile(path,JSON.stringify([{content:"json post",scheduledAt:"",notes:"memo"}]));expect(await readPostCandidates(path)).toEqual([{content:"json post",scheduledAt:"",notes:"memo"}]);});
});
