import { google, type Auth, type sheets_v4 } from "googleapis";
import type { PostHistoryRecord, PostQueueRecord, PostStore, PublisherRunLogRecord, PublisherRunStore } from "./types.js";
const QUEUE = "PostQueue", HISTORY = "PostHistory", RUN_LOG = "PublisherRunLog";
const QH = ["postId","platform","content","contentHash","status","scheduledAt","approvedAt","createdAt","updatedAt","publishedAt","threadsPostId","errorCode","errorMessage","retryCount","source","notes","requestedScheduledAt"];
const HH = ["historyId","postId","platform","contentHash","scheduledAt","publishedAt","status","threadsPostId","attempt","errorCode","createdAt"];
const RH = ["runId","startedAt","finishedAt","dueCount","publishedCount","failedCount","expiredCount","skippedCount","overallStatus"];
export class GoogleSheetsPostStore implements PostStore, PublisherRunStore {
  private sheets: sheets_v4.Sheets; constructor(auth: Auth.OAuth2Client, private id: string) { this.sheets = google.sheets({ version: "v4", auth }); }
  async ensurePostSheets() { const meta = await this.sheets.spreadsheets.get({ spreadsheetId: this.id }); const existing = new Set(meta.data.sheets?.map((s)=>s.properties?.title)); const requests = [QUEUE,HISTORY,RUN_LOG].filter((x)=>!existing.has(x)).map((title)=>({addSheet:{properties:{title,gridProperties:{frozenRowCount:1}}}})); if(requests.length) await this.sheets.spreadsheets.batchUpdate({spreadsheetId:this.id,requestBody:{requests}}); for(const [sheet,header] of [[QUEUE,QH],[HISTORY,HH],[RUN_LOG,RH]] as const){ const r=await this.sheets.spreadsheets.values.get({spreadsheetId:this.id,range:`'${sheet}'!1:1`}); if(JSON.stringify(r.data.values?.[0]??[])!==JSON.stringify(header)) await this.sheets.spreadsheets.values.update({spreadsheetId:this.id,range:`'${sheet}'!A1`,valueInputOption:"RAW",requestBody:{values:[header]}}); } }
  async listPosts(): Promise<PostQueueRecord[]> { const r=await this.sheets.spreadsheets.values.get({spreadsheetId:this.id,range:`'${QUEUE}'!A2:Q`}); return (r.data.values??[]).map(x=>({postId:String(x[0]??""),platform:"threads",content:String(x[2]??""),contentHash:String(x[3]??""),status:String(x[4]) as PostQueueRecord["status"],scheduledAt:String(x[5]??""),approvedAt:String(x[6]??""),createdAt:String(x[7]??""),updatedAt:String(x[8]??""),publishedAt:String(x[9]??""),threadsPostId:String(x[10]??""),errorCode:String(x[11]??"") as PostQueueRecord["errorCode"],errorMessage:String(x[12]??""),retryCount:Number(x[13]??0),source:String(x[14]??"manual") as PostQueueRecord["source"],notes:String(x[15]??""),requestedScheduledAt:String(x[16]??"")})); }
  async getPost(postId:string){ return (await this.listPosts()).find(x=>x.postId===postId)??null; }
  private values(p:PostQueueRecord){return [p.postId,p.platform,p.content,p.contentHash,p.status,p.scheduledAt,p.approvedAt,p.createdAt,p.updatedAt,p.publishedAt,p.threadsPostId,p.errorCode,p.errorMessage,p.retryCount,p.source,p.notes,p.requestedScheduledAt];}
  async upsertPost(p:PostQueueRecord){const posts=await this.listPosts(), row=posts.findIndex(x=>x.postId===p.postId); if(row>=0) await this.sheets.spreadsheets.values.update({spreadsheetId:this.id,range:`'${QUEUE}'!A${row+2}:Q${row+2}`,valueInputOption:"RAW",requestBody:{values:[this.values(p)]}}); else await this.sheets.spreadsheets.values.append({spreadsheetId:this.id,range:`'${QUEUE}'!A:Q`,valueInputOption:"RAW",insertDataOption:"INSERT_ROWS",requestBody:{values:[this.values(p)]}});}
  async appendHistory(h:PostHistoryRecord){await this.sheets.spreadsheets.values.append({spreadsheetId:this.id,range:`'${HISTORY}'!A:K`,valueInputOption:"RAW",insertDataOption:"INSERT_ROWS",requestBody:{values:[[h.historyId,h.postId,h.platform,h.contentHash,h.scheduledAt,h.publishedAt,h.status,h.threadsPostId,h.attempt,h.errorCode,h.createdAt]]}});}
  async appendPublisherRunLog(r:PublisherRunLogRecord){await this.ensurePostSheets();await this.sheets.spreadsheets.values.append({spreadsheetId:this.id,range:`'${RUN_LOG}'!A:I`,valueInputOption:"RAW",insertDataOption:"INSERT_ROWS",requestBody:{values:[[r.runId,r.startedAt,r.finishedAt,r.dueCount,r.publishedCount,r.failedCount,r.expiredCount,r.skippedCount,r.overallStatus]]}});}
}
