import { google,type Auth,type sheets_v4 } from "googleapis";
import type { ContentAIRunLog,ContentLedgerRecord,ContentPlanRecord,ContentStore } from "./types.js";
const PLAN="ContentPlan",LEDGER="ContentLedger",LOG="ContentAIRunLog";
const PH=["planId","targetDate","slot","contentPillar","coreTheme","angle","goal","hookIdea","status","generatedPostId","createdAt","updatedAt","notes","regenerationCount"];
const LH=["contentId","postId","platform","createdAt","publishedAt","status","coreTheme","claim","readerValue","advice","contentPillar","angle","hookType","contentSummary","sourceType","performanceTier","notes"];
const AH=["runId","startedAt","finishedAt","provider","model","operation","requestedCount","generatedCount","uniqueCount","reviewCount","duplicateCount","failedCount","estimatedInputTokens","estimatedOutputTokens","status","createdAt"];
const objects=(values:unknown[][])=>{const [h=[], ...rows]=values;return rows.filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(h.map((x,i)=>[String(x),r[i]??""])));};
export class GoogleSheetsContentStore implements ContentStore{private sheets:sheets_v4.Sheets;constructor(auth:Auth.OAuth2Client,private id:string){this.sheets=google.sheets({version:"v4",auth});}
 async ensureContentSheets(){const meta=await this.sheets.spreadsheets.get({spreadsheetId:this.id});const existing=new Set(meta.data.sheets?.map(s=>s.properties?.title));const requests=[PLAN,LEDGER,LOG].filter(x=>!existing.has(x)).map(title=>({addSheet:{properties:{title,gridProperties:{frozenRowCount:1}}}}));if(requests.length)await this.sheets.spreadsheets.batchUpdate({spreadsheetId:this.id,requestBody:{requests}});for(const [sheet,header] of [[PLAN,PH],[LEDGER,LH],[LOG,AH]] as const){const r=await this.sheets.spreadsheets.values.get({spreadsheetId:this.id,range:`'${sheet}'!1:1`});if(JSON.stringify(r.data.values?.[0]??[])!==JSON.stringify(header))await this.sheets.spreadsheets.values.update({spreadsheetId:this.id,range:`'${sheet}'!A1`,valueInputOption:"RAW",requestBody:{values:[header]}});}}
 async listPlans(){await this.ensureContentSheets();const r=await this.sheets.spreadsheets.values.get({spreadsheetId:this.id,range:`'${PLAN}'!A2:N`});return objects(r.data.values??[]).map(x=>({planId:String(x.planId),targetDate:String(x.targetDate),slot:String(x.slot),contentPillar:String(x.contentPillar),coreTheme:String(x.coreTheme),angle:String(x.angle),goal:String(x.goal),hookIdea:String(x.hookIdea),status:String(x.status) as ContentPlanRecord["status"],generatedPostId:String(x.generatedPostId),createdAt:String(x.createdAt),updatedAt:String(x.updatedAt),notes:String(x.notes),regenerationCount:Number(x.regenerationCount||0)}));}
 private pv(x:ContentPlanRecord){return[x.planId,x.targetDate,x.slot,x.contentPillar,x.coreTheme,x.angle,x.goal,x.hookIdea,x.status,x.generatedPostId,x.createdAt,x.updatedAt,x.notes,x.regenerationCount];}
 async upsertPlan(x:ContentPlanRecord){const all=await this.listPlans(),i=all.findIndex(y=>y.planId===x.planId),row=this.pv(x);if(i>=0)await this.sheets.spreadsheets.values.update({spreadsheetId:this.id,range:`'${PLAN}'!A${i+2}:N${i+2}`,valueInputOption:"RAW",requestBody:{values:[row]}});else await this.sheets.spreadsheets.values.append({spreadsheetId:this.id,range:`'${PLAN}'!A:N`,valueInputOption:"RAW",insertDataOption:"INSERT_ROWS",requestBody:{values:[row]}});}
 async listLedger(){await this.ensureContentSheets();const r=await this.sheets.spreadsheets.values.get({spreadsheetId:this.id,range:`'${LEDGER}'!A2:Q`});return objects(r.data.values??[]).map(x=>({...x,platform:"threads",performanceTier:String(x.performanceTier) as ContentLedgerRecord["performanceTier"]})) as unknown as ContentLedgerRecord[];}
 private lv(x:ContentLedgerRecord){return LH.map(k=>x[k as keyof ContentLedgerRecord]??"");}
 async upsertLedger(x:ContentLedgerRecord){const all=await this.listLedger(),i=all.findIndex(y=>y.contentId===x.contentId),row=this.lv(x);if(i>=0)await this.sheets.spreadsheets.values.update({spreadsheetId:this.id,range:`'${LEDGER}'!A${i+2}:Q${i+2}`,valueInputOption:"RAW",requestBody:{values:[row]}});else await this.sheets.spreadsheets.values.append({spreadsheetId:this.id,range:`'${LEDGER}'!A:Q`,valueInputOption:"RAW",insertDataOption:"INSERT_ROWS",requestBody:{values:[row]}});}
 async appendRunLog(x:ContentAIRunLog){await this.ensureContentSheets();await this.sheets.spreadsheets.values.append({spreadsheetId:this.id,range:`'${LOG}'!A:P`,valueInputOption:"RAW",insertDataOption:"INSERT_ROWS",requestBody:{values:[[x.runId,x.startedAt,x.finishedAt,x.provider,x.model,x.operation,x.requestedCount,x.generatedCount,x.uniqueCount,x.reviewCount,x.duplicateCount,x.failedCount,x.estimatedInputTokens,x.estimatedOutputTokens,x.status,x.createdAt]]}});}
 async readThreadsPerformance(){const r=await this.sheets.spreadsheets.values.get({spreadsheetId:this.id,range:"'ContentMetrics'!A:Q"});return objects(r.data.values??[]).filter(x=>x.platform==="threads").map(x=>({contentId:String(x.contentId),views:Number(x.views||0),likes:Number(x.likes||0),replies:Number(x.replies||0),reposts:Number(x.reposts||0)}));}
}
