import type { PostStatus } from "../posting/types.js";
import type { ContentPlanRecord, DuplicateStatus } from "../content-ai/types.js";
import type { PostingDashboardOutput, PostingDashboardRaw, PostingDashboardRow } from "./types.js";

const STATUS_JA:Record<string,string>={DRAFT:"下書き",REVIEW:"要確認",APPROVED:"承認済",SCHEDULED:"予約済",PUBLISHING:"投稿処理中",PUBLISHED:"投稿済",FAILED:"エラー",CANCELLED:"却下/キャンセル",SKIPPED_DUPLICATE:"重複除外",EXPIRED:"期限切れ",PLANNED:"企画済",GENERATED:"生成済",REJECTED:"却下",};
const SOURCE_JA:Record<string,string>={manual:"手動",import:"一括取込",AI_CONTENT_PHASE3:"AI案",future_ai:"AI案"};
const DUP_JA:Record<DuplicateStatus|string,string>={UNIQUE:"重複なし",POSSIBLE_DUPLICATE:"類似あり",DUPLICATE:"重複"};
const STATUS_ORDER:Record<string,number>={要確認:0,下書き:1,承認済:2,予約済:3,投稿処理中:4,エラー:5,期限切れ:6,投稿済:7,"却下/キャンセル":8,重複除外:9,企画済:10,生成済:11,却下:12};
export const statusJapanese=(status:string)=>STATUS_JA[status]??status;
export const sourceJapanese=(source:string)=>SOURCE_JA[source]??(source||"未設定");
export const duplicateJapanese=(status:string)=>DUP_JA[status]??"未判定";
const localParts=(value:string)=>{if(!value||!Number.isFinite(Date.parse(value)))return{date:"",time:"",dateTime:""};const d=new Date(value),parts=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(d),get=(x:Intl.DateTimeFormatPartTypes)=>parts.find(p=>p.type===x)?.value??"",date=`${get("year")}-${get("month")}-${get("day")}`,time=`${get("hour")}:${get("minute")}`;return{date,time,dateTime:`${date} ${time}`};};
const dateAtTokyo=(date:string,time="00:00")=>Date.parse(`${date}T${time}:00+09:00`);
export function tokyoWeek(asOf:string){const d=new Date(`${asOf}T00:00:00Z`),day=(d.getUTCDay()+6)%7,start=new Date(d.getTime()-day*86400000),end=new Date(start.getTime()+6*86400000);return{start:start.toISOString().slice(0,10),end:end.toISOString().slice(0,10)};}
function planForPost(plans:ContentPlanRecord[],postId:string,notes:string){const fromId=plans.find(p=>p.generatedPostId===postId);if(fromId)return fromId;const id=notes.match(/(?:^|;)\s*planId=([^;]+)/)?.[1]?.trim();return id?plans.find(p=>p.planId===id):undefined;}
function duplicateFrom(notes:string,status:string,plan?:ContentPlanRecord){if(status==="SKIPPED_DUPLICATE"||plan?.status==="SKIPPED_DUPLICATE")return"DUPLICATE";return notes.match(/semantic=(UNIQUE|POSSIBLE_DUPLICATE|DUPLICATE)/)?.[1]??"";}
export function buildPostingDashboard(raw:PostingDashboardRaw,asOf:string,now=new Date()):PostingDashboardOutput{
 const week=tokyoWeek(asOf),ledgerByPost=new Map(raw.ledger.filter(x=>x.postId).map(x=>[x.postId,x])),historyByPost=new Map<string,typeof raw.history[number]>();for(const h of raw.history){const old=historyByPost.get(h.postId);if(!old||h.createdAt>old.createdAt)historyByPost.set(h.postId,h);}
 const rows:PostingDashboardRow[]=raw.posts.map(post=>{const plan=planForPost(raw.plans,post.postId,post.notes),ledger=ledgerByPost.get(post.postId),history=historyByPost.get(post.postId),scheduled=localParts(post.scheduledAt),published=localParts(post.publishedAt||history?.publishedAt||""),created=localParts(post.createdAt),date=plan?.targetDate||scheduled.date||published.date||created.date,time=plan?.slot||scheduled.time||published.time||created.time,duplicate=duplicateFrom(post.notes,post.status,plan);return{postDate:date,postTime:time,content:post.content,status:statusJapanese(post.status),contentPillar:ledger?.contentPillar||plan?.contentPillar||"未設定",coreTheme:ledger?.coreTheme||plan?.coreTheme||"未設定",duplicateStatus:duplicateJapanese(duplicate),scheduledAt:scheduled.dateTime,publishedAt:published.dateTime,source:sourceJapanese(post.source),notes:post.notes,isCurrentWeek:date>=week.start&&date<=week.end,sortAt:date&&time?`${date} ${time}`:"9999-12-31 23:59"};});
 const represented=new Set(raw.posts.map(p=>planForPost(raw.plans,p.postId,p.notes)?.planId).filter(Boolean));for(const plan of raw.plans.filter(p=>!represented.has(p.planId))){rows.push({postDate:plan.targetDate,postTime:plan.slot,content:"",status:statusJapanese(plan.status),contentPillar:plan.contentPillar||"未設定",coreTheme:plan.coreTheme||"未設定",duplicateStatus:duplicateJapanese(plan.status==="SKIPPED_DUPLICATE"?"DUPLICATE":""),scheduledAt:"",publishedAt:"",source:"AI案",notes:plan.notes,isCurrentWeek:plan.targetDate>=week.start&&plan.targetDate<=week.end,sortAt:`${plan.targetDate} ${plan.slot}`});}
 rows.sort((a,b)=>Number(b.isCurrentWeek)-Number(a.isCurrentWeek)||a.sortAt.localeCompare(b.sortAt)||(STATUS_ORDER[a.status]??99)-(STATUS_ORDER[b.status]??99));
 const current=rows.filter(r=>r.isCurrentWeek),count=(value:string)=>current.filter(r=>r.status===value).length,next=raw.posts.filter(p=>p.status==="SCHEDULED"&&Date.parse(p.scheduledAt)>now.getTime()).sort((a,b)=>a.scheduledAt.localeCompare(b.scheduledAt))[0];
 return{summary:{weekStart:week.start,weekEnd:week.end,planned:current.length,draft:count("下書き"),review:count("要確認"),approved:count("承認済"),scheduled:count("予約済"),published:count("投稿済"),failed:count("エラー"),nextScheduled:next?localParts(next.scheduledAt).dateTime:"なし",generatedAt:now.toISOString()},rows};
}
